### ISSUE TITLE
NameError: global name 'win32crypt' is not defined

### ISSUE THREAD

**Issue by 0bytedna** [Ierofantis/Chrome_Venom#3]
C:\Python27>python.exe chrome_venom.py
Traceback (most recent call last):
  File "chrome_venom.py", line 131, in <module>
    mail()
  File "chrome_venom.py", line 25, in mail
    print main()
  File "chrome_venom.py", line 67, in main
    password = win32crypt.CryptUnprotectData(information[2], None, None, None, 0)[1]
NameError: global name 'win32crypt' is not defined

**Comment by mmaatuq** [comment]
try another version of python python 2.7 for example
